FROM node:20-alpine AS build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

ARG VITE_API_BASE_URL=http://localhost:5000
ARG VITE_KIBANA_URL=http://localhost:5601
ARG VITE_APP_NAME=Sentinel IoT
ARG VITE_ENABLE_KIBANA_EMBED=true
ARG VITE_DEFAULT_LIMIT=50
ARG VITE_REQUEST_TIMEOUT_MS=10000
ARG VITE_AUTH_MODE=mock

ENV VITE_API_BASE_URL=${VITE_API_BASE_URL}
ENV VITE_KIBANA_URL=${VITE_KIBANA_URL}
ENV VITE_APP_NAME=${VITE_APP_NAME}
ENV VITE_ENABLE_KIBANA_EMBED=${VITE_ENABLE_KIBANA_EMBED}
ENV VITE_DEFAULT_LIMIT=${VITE_DEFAULT_LIMIT}
ENV VITE_REQUEST_TIMEOUT_MS=${VITE_REQUEST_TIMEOUT_MS}
ENV VITE_AUTH_MODE=${VITE_AUTH_MODE}

RUN npm run build

FROM nginx:1.27-alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]